services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: auth_db_api
    restart: always
    ports:
      - "${API_PORT}:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
